{% set name = "cppadcodegen" %}
{% set version = "2.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/joaoleal/CppADCodeGen/archive/v{{ version }}.tar.gz
  sha256: 2a08c900d2f9df6d2fbdced6d3f67c6227cf5871ee3cf666d199e912c26c3a58

build:
  number: 0
  # No ABI policy documented, let's be conservative 
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [linux]
  host:
    - cppad

test:
  commands:
    - test -d ${PREFIX}/include/cppad/cg  # [unix]
    - test -f ${PREFIX}/share/pkgconfig/cppadcg.pc  # [unix]
    - if not exist %PREFIX%\\Library\\include\\cppad\cg exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\pkgconfig\\cppadcg.pc exit 1  # [win]

about:
  home: https://github.com/joaoleal/CppADCodeGen
  license: GPL-3.0-only OR EPL-2.0
  license_file:
    - gpl3.txt
    - epl-v10.txt
  summary: CppADCodeGen - Source Code Generation for Automatic Differentiation using Operator Overloading

  dev_url: https://github.com/joaoleal/CppADCodeGen

extra:
  recipe-maintainers:
    - jorisv
    - traversaro
    - jcarpent
